#!/usr/bin/env sh
x=$(xdpyinfo | grep "dimensions" | awk '{ print $2 }' | awk -F 'x' '{ print $1}')
y=$(xdpyinfo | grep "dimensions" | awk '{ print $2 }' | awk -F 'x' '{ print $2}')
if i3-msg -t get_tree | grep -Fq '"class":"i3bar"'; then
    xdotool mousemove $x $y
    i3-msg "workspace 11"
    i3-msg bar mode invisible
    i3-msg exec --no-startup-id "unclutter -idle 0"
else
    xdotool mousemove $(($x/2)) $(($y/2))
    # i3-msg "workspace 1"
    i3-msg "workspace back_and_forth"
    i3-msg bar mode dock
fi
exit 1